version: '3.9'

services:
  example_pg_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5445:5432

volumes:
  postgres_data:
networks:
  default:
    name: example-work-with-pg-net
